version: "3.8"
services:
  server:
    image: server
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./upload:/opt/uploads
    restart: always
    networks:
      - server

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    command: server /data --console-address :9001
    networks:
      - server
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - server
    restart: unless-stopped

networks:
  server:
    name: app
    driver: bridge